### ISSUE TITLE
Embedded form elements become disabled

### ISSUE THREAD

**Issue by jbingel** [callesg/google_form_javascript_css#1]
I've embedded a simple form following the example:

```
<div id="formarea" class="flex flex-col w-3/6" >  
        <?php

        if(!isset($_GET['url'])){
            //the url to the google form
            $_GET['url'] = 'https://docs.google.com/forms/d/e/1FAIpQLSd5x77O6rgs6zvdpHcZHrzxb_wlmNne-gsvSClhtbdVMkIRaQ/viewform?embedded=true';
        }
        include("../resources/php/form.php"); //include the google form 
        ?>   
</div>   

<style>
  /* make the backgound red*/
.freebirdFormviewerViewHeaderTitleRow{
	background-color: red!important;
	color: black !important;
}
```
I can see the effect of the introduced styling, but the form elements become disabled (bearing class `isDisabled` on a `label` element or `disabled` attributes for `input` elements). Even if I remove these manually, clicking responses does not have any effect (such as highlighting the clicked answer). Clicking the "Submit" has no effect either.

**Comment by calledit** [comment]
Might be cause you are trying to insert the form in to an existing website or it looks like you are.

The end result for the client will be something like:
<html>
<header>
Your headers with your own stuff
</header>
<body>
<div>

<html>
<header>
Googles headers
</header>
<body>
</body>
</html>

</div>
</body>
</html>

And the include part with the if statement has to go at the very top of the page.

**Comment by jbingel** [comment]
Gotcha, makes sense. I've tried it with a bare-bones solution that just replicates your `example.php` with my own Google Form. The elements are now no longer disabled, but unfortunately clicking the button does not have any effect. The embedded form does not display an "Answers received" message, responses don't arrive at my Form, and the console doe not print any error.

**Comment by calledit** [comment]
The example works fine for me. Which I interpret as you are "doing" something "wrong", rather than the scripts or google not working properly.

Maybe the "cross site XHR proxy" part of the script is malfunctioning due to something with which folder you placed the scripts. Check the network tab of the browser console to see if you are getting failed network requests.
